#include "../../src/macro_collections.h"

CMC_COLLECTION_GENERATE_HEADER(LIST, l, list, /* K */, int)
CMC_COLLECTION_GENERATE_HEADER(STACK, s, stack, /* K */, int)
CMC_COLLECTION_GENERATE_HEADER(QUEUE, q, queue, /* K */, int)
CMC_COLLECTION_GENERATE_HEADER(DEQUE, d, deque, /* K */, int)
CMC_COLLECTION_GENERATE_HEADER(LINKEDLIST, ll, linked, /* K */, int)
CMC_COLLECTION_GENERATE_HEADER(HEAP, h, heap, /* K */, int)
CMC_COLLECTION_GENERATE_HEADER(TREESET, ts, tset, /* K */, int)
CMC_COLLECTION_GENERATE_HEADER(TREEMAP, tm, tmap, int, int)
CMC_COLLECTION_GENERATE_HEADER(HASHSET, hs, hset, /* K */, int)
CMC_COLLECTION_GENERATE_HEADER(HASHMAP, hm, hmap, int, int)

CMC_COLLECTION_GENERATE_HEADER(INTERVALHEAP, ih, iheap, , int)
CMC_COLLECTION_GENERATE_HEADER(MULTIMAP, mm, mmap, int, int)
CMC_COLLECTION_GENERATE_HEADER(MULTISET, ms, mset, , int)
