/**
 * ext_cmc_bitset.h
 *
 * Creation Date: 08/06/2020
 *
 * Authors:
 * Leonardo Vencovsky (https://github.com/LeoVen)
 *
 */

#ifndef CMC_EXT_CMC_BITSET_H
#define CMC_EXT_CMC_BITSET_H

#include "cor_core.h"

/**
 * All the EXT parts of CMC BitSet.
 */
#define CMC_EXT_CMC_BITSET_PARTS PLACEHOLDER

#define CMC_EXT_CMC_BITSET_PLACEHOLDER(ACCESS, FILE, PARAMS) \
    CMC_(CMC_(CMC_EXT_CMC_BITSET_PLACEHOLDER_, ACCESS), CMC_(_, FILE))(PARAMS)

#define CMC_EXT_CMC_BITSET_PLACEHOLDER_PUBLIC_HEADER(PARAMS)

#define CMC_EXT_CMC_BITSET_PLACEHOLDER_PUBLIC_SOURCE(PARAMS)

#define CMC_EXT_CMC_BITSET_PLACEHOLDER_PRIVATE_HEADER(PARAMS)

#define CMC_EXT_CMC_BITSET_PLACEHOLDER_PRIVATE_SOURCE(PARAMS)

#endif /* CMC_EXT_CMC_BITSET_H */
